server:
  #指定服务端口
  port: 7001
eureka:
  #指定主机名称
  instance:
    hostname: eureka7001.com
  #server一定程度上也是client，互为client，
  client:
    #由于自己就是服务器，不需要注册到自己
    register-with-eureka: false
    #由于自己就是服务器，不需要从服务器获取注册信息
    fetch-registry: false
    #服务地址s
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
